---
- name: Manage Postfix mail server
  hosts: remote
  become: yes
  tasks:
    - name: Install Postfix
      package:
        name: postfix
        state: present
      when: "'init postfix' in ansible_run_tags"

    - name: Start and enable Postfix service
      service:
        name: postfix
        state: started
        enabled: yes
      when: "'init postfix' in ansible_run_tags"

    - name: Remove Postfix
      package:
        name: postfix
        state: absent
      when: "'drop postfix' in ansible_run_tags"