---
# Название playbook: Установка Nginx
- name: Установить Nginx
  hosts: remote
  become: yes  # Использование sudo для выполнения команд
  tasks:
    # Проверка, что Docker установлен
    - name: Проверить, что Docker установлен
      fail:
        msg: "Docker не установлен. Запустите playbooks/docker/install.yml сначала."
      when: "'docker_installed' not in ansible_facts"

    # Установка Nginx
    - name: Установить Nginx
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    # Запуск и включение службы Nginx
    - name: Запустить и включить службу Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # Отметить, что Nginx установлен
    - name: Установить факт завершения установки Nginx
      set_fact:
        nginx_installed: true
